Repository 2023SB-TeamJ/2023SB-Team-J, pull requests merged in 2023-07, with the labels that each got.

#2 [front/feat/#1] 로그인 / 회원가입 Modal 컴포넌트 구현
  frontend/src/components/App.js
  frontend/src/components/AuthModalStyle.jsx
  frontend/src/components/LoginModal.jsx
  frontend/src/components/SignUpModal.jsx
  frontend/src/test/AuthModalTest.jsx
Labels: enhancement

#6 Back/fix/#5
  backend/Dockerfile
  backend/backend_project/settings.py
  backend/common/views.py
  backend/image/models.py
  backend/image/views.py
  backend/requirements.txt
  docker-compose.yml
Labels: bug

#9 [front/feat/#8] 페이지 라우팅 작업
  frontend/src/Router.jsx
  frontend/src/pages/Album.jsx
  frontend/src/pages/ChooseFrame.jsx
  frontend/src/pages/ConvertAI.jsx
  frontend/src/pages/Customizing.jsx
  frontend/src/pages/Main.jsx
  frontend/src/pages/UploadImage.jsx
Labels: enhancement

#15 [front/feat/#4] 이미지 업로드 컴포넌트 구현
  frontend/.eslintrc.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/font/BMDOHYEON_otf.otf
  frontend/src/assets/font/BMDOHYEON_ttf.ttf
  frontend/src/assets/images/SampleUploadImage.png
  frontend/src/assets/images/logo.jpg
  frontend/src/components/LoginModal.jsx
  frontend/src/components/SignUpModal.jsx
  frontend/src/components/UploadImage.jsx
  frontend/src/pages/Main.jsx
Labels: enhancement

#20 fix: 실사네컷 반환 api request 방식 수정
  backend/backend_project/settings.py
  backend/common/admin.py
  backend/common/models.py
  backend/common/views.py
  backend/image/views.py
Labels: enhancement

#23 fix : 로그인/로그아웃/회원가입 버튼, 제목 버그 수정
  frontend/src/components/SignBtn.jsx
  frontend/src/components/StartBtn.jsx
  frontend/src/components/Title.jsx
Labels: bug

#33 front/design/#28 4개 페이지 기초 디자인 레이아웃 작업/ 로고,제목 등 일부 컴포넌트 수정
  frontend/src/components/Header.jsx
  frontend/src/components/Logo.jsx
  frontend/src/components/Name.jsx
  frontend/src/components/SignBtn.jsx
  frontend/src/components/Title.jsx
  frontend/src/pages/ChooseFramePage.jsx
  frontend/src/pages/ConvertAIPage.jsx
  frontend/src/pages/CustomizingPage.jsx
  frontend/src/pages/UploadImagePage.jsx
Labels: enhancement, style

#37 [front/feat/#30] 앨범 페이지 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/images/plusBtn.png
  frontend/src/components/AlbumDetailModal.jsx
  frontend/src/components/HeaderAlbum.jsx
  frontend/src/components/Logo.jsx
  frontend/src/components/Name.jsx
  frontend/src/components/UploadBtn.jsx
  frontend/src/pages/AlbumPage.jsx
  frontend/src/pages/TestPage.jsx
  frontend/src/styles/GlobalStyle.js
Labels: enhancement, style

#42 [front/feat/#36] 로딩 페이지 구현
  frontend/src/pages/LoadingPage.jsx
Labels: enhancement, style

#45 [front/feat/#27] 메인페이지 구현 완료
  frontend/src/assets/images/1x4sampleImage.png
  frontend/src/assets/images/2x2sampleImage.jpg
  frontend/src/components/AlbumDetailModal.jsx
  frontend/src/components/AuthModalStyle.jsx
  frontend/src/components/HeaderMain.jsx
  frontend/src/components/LoginModal.jsx
  frontend/src/components/SignUpModal.jsx
  frontend/src/components/StartBtn.jsx
  frontend/src/pages/MainPage.jsx
Labels: style

#62 앨범 조회 연동 테스트_1
  docker-compose.yml
  frontend/.eslintrc.js
  frontend/db.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/Router.jsx
  frontend/src/assets/font/BMDOHYEON_otf.otf
  frontend/src/assets/font/BMDOHYEON_ttf.ttf
  frontend/src/assets/images/1x4sampleImage.png
  frontend/src/assets/images/2x2sampleImage.jpg
  frontend/src/assets/images/SampleUploadImage.png
  frontend/src/assets/images/logo.jpg
  frontend/src/assets/images/logoImage.png
  frontend/src/assets/images/logoText.png
  frontend/src/assets/images/photo1.png
  frontend/src/assets/images/plusBtn.png
  frontend/src/components/AlbumDetailModal.jsx
  frontend/src/components/AuthModalStyle.jsx
  frontend/src/components/Header.jsx
  frontend/src/components/HeaderAlbum.jsx
  frontend/src/components/HeaderMain.jsx
  frontend/src/components/LeftAIShift.jsx
  frontend/src/components/LoginModal.jsx
  frontend/src/components/Logo.jsx
  frontend/src/components/Name.jsx
  frontend/src/components/PageShiftBtn.jsx
  frontend/src/components/RightAIShift.jsx
  frontend/src/components/SignBtn.jsx
  frontend/src/components/SignUpModal.jsx
  frontend/src/components/Title.jsx
  frontend/src/components/UploadBtn.jsx
  frontend/src/components/UploadImage.jsx
  frontend/src/font.css
  frontend/src/pages/AlbumPage.jsx
  frontend/src/pages/ChooseFramePage.jsx
  frontend/src/pages/ConvertAIPage.jsx
  frontend/src/pages/CustomizingPage.jsx
  frontend/src/pages/LoadingPage.jsx
  frontend/src/pages/Main.jsx
  frontend/src/pages/MainPage.jsx
  frontend/src/pages/TestPage.jsx
  frontend/src/pages/UploadImagePage.jsx
  frontend/src/styles/GlobalStyle.js
  frontend/src/styles/theme.js
  frontend/src/test/AuthModalTest.jsx
Labels: enhancement

#72 [Back/feat] 앨범 상세 조회 API, 앨범 전체 조회 API 병합 작업
  backend/album/models.py
  backend/album/serializers.py
  backend/album/urls.py
  backend/album/views.py
  backend/backend_project/settings.py
  backend/backend_project/urls.py
  backend/image/migrations/0001_initial.py
  backend/image/migrations/__init__.py
  backend/image/views.py
  frontend/src/components/AlbumDetailModal.jsx
  prometheus/prometheus-volume/data/01H5JBFSC4BS861MNQJGDQJ385/chunks/000001
  prometheus/prometheus-volume/data/01H5JBFSC4BS861MNQJGDQJ385/index
  prometheus/prometheus-volume/data/01H5JBFSC4BS861MNQJGDQJ385/meta.json
  prometheus/prometheus-volume/data/01H5JBFSC4BS861MNQJGDQJ385/tombstones
  prometheus/prometheus-volume/data/01H5JBFT10BTRYJS73V431EAPW/chunks/000001
  prometheus/prometheus-volume/data/01H5JBFT10BTRYJS73V431EAPW/index
  prometheus/prometheus-volume/data/01H5JBFT10BTRYJS73V431EAPW/meta.json
  prometheus/prometheus-volume/data/01H5JBFT10BTRYJS73V431EAPW/tombstones
  prometheus/prometheus-volume/data/01H5KJP4ZT9AJYTJWSVSHEHJ7A/chunks/000001
  prometheus/prometheus-volume/data/01H5KJP4ZT9AJYTJWSVSHEHJ7A/index
  prometheus/prometheus-volume/data/01H5KJP4ZT9AJYTJWSVSHEHJ7A/meta.json
  prometheus/prometheus-volume/data/01H5KJP4ZT9AJYTJWSVSHEHJ7A/tombstones
  prometheus/prometheus-volume/data/wal/00000050
  prometheus/prometheus-volume/data/wal/00000051
  prometheus/prometheus-volume/data/wal/00000052
  prometheus/prometheus-volume/data/wal/checkpoint.00000049/00000000
Labels: enhancement

#75 Front/feat/#43 캐러셀 기능 구현
  frontend/src/assets/images/image1.png
  frontend/src/assets/images/image2.png
  frontend/src/assets/images/image3.png
  frontend/src/assets/images/image4.png
  frontend/src/components/Carousel.jsx
  frontend/src/pages/ConvertAIPage.jsx
Labels: enhancement

#80 [front/feat/#34] 커스터 마이징 페이지 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/images/4cut_test.png
  frontend/src/assets/images/addphoto.png
  frontend/src/assets/images/photo.png
  frontend/src/assets/images/sticker.png
  frontend/src/assets/images/sticker_heart.png
  frontend/src/assets/images/sticker_smile.png
  frontend/src/assets/images/sticker_sunglass.png
  frontend/src/assets/images/textbox.png
  frontend/src/components/Custom/CustomMenuBar.jsx
  frontend/src/components/Custom/CustomPhoto.jsx
  frontend/src/components/Custom/CustomSticker.jsx
  frontend/src/components/Custom/CustomTextBox.jsx
  frontend/src/components/Custom/StickerList.jsx
  frontend/src/pages/CustomizingPage.jsx
Labels: enhancement, style

#82 [Back/feat/#56] 앨범 조회 api, 앨범 상세 조회 api => 로그인/로그아웃/회원가입 api merge 작업
  backend/album/serializers.py
  backend/album/urls.py
  backend/album/views.py
  backend/backend_project/settings.py
  backend/requirements.txt
  docker-compose.yml
  frontend/db.json
  frontend/src/Router.jsx
  frontend/src/components/AlbumDetailModal.jsx
  frontend/src/components/Header.jsx
  frontend/src/components/Loading.jsx
  frontend/src/components/LoginModal.jsx
  frontend/src/components/SignUpModal.jsx
  frontend/src/index.jsx
  frontend/src/pages/AlbumPage.jsx
  frontend/src/pages/MainPage.jsx
Labels: enhancement

#83 [front/feat/#47] PageShiftBtn, ChooseFramePage, ConvertAIPage, UploadImagePage 코드 일부 수정
  frontend/src/components/PageShiftBtn.jsx
  frontend/src/pages/ChooseFramePage.jsx
  frontend/src/pages/ConvertAIPage.jsx
  frontend/src/pages/UploadImagePage.jsx
Labels: enhancement

#96 [Back/feat/#94]앨범 조회 및 앨범 상세 조회 api 오류 해결
  backend/album/serializers.py
  backend/album/views.py
  docker-compose.yml
Labels: bug

#100 프론트 코드 수정해서 다시 PR
  backend/image/views.py
  frontend/src/pages/AlbumPage.jsx
  frontend/src/pages/CustomizingPage.jsx
Labels: enhancement

#104 [frontend] 프레임/색상 변환 기능과 이미지/url 넘기는 기능 구현
  frontend/src/Router.jsx
  frontend/src/assets/images/BlackImg.png
  frontend/src/assets/images/Brown.png
  frontend/src/assets/images/Green.png
  frontend/src/assets/images/Solid_gray.png
  frontend/src/components/Custom/CustomCarousel.jsx
  frontend/src/pages/ConvertAIPage.jsx
  frontend/src/pages/CustomizingPage.jsx
  frontend/src/pages/FramePage.jsx
Labels: enhancement

#109 [front/design/#108] 로그인 모달 비밀번호 확인 삭제
  backend/image/AiModels.py
  docker-compose.yml
  frontend/package-lock.json
  frontend/src/components/LoginModal.jsx
Labels: style

#111 [Back/feat] 최종 이미지 업로드 API 재연동
  backend/image/views.py
  docker-compose.yml
Labels: bug

#122 [front/chore/#121] 로그인 / 회원가입 시 라우팅 대신 모달창 꺼짐으로 변경, 로그아웃 버튼 메인페이지 라우팅
  frontend/src/components/Header.jsx
  frontend/src/components/HeaderAlbum.jsx
  frontend/src/components/LoginModal.jsx
  frontend/src/components/SignUpModal.jsx
  grafana/grafana-volume/grafana.db
  grafana/grafana-volume/plugins/grafana-clock-panel/MANIFEST.txt
  grafana/grafana-volume/plugins/grafana-simple-json-datasource/MANIFEST.txt
  grafana/grafana-volume/plugins/grafana-simple-json-datasource/img/simpleJson_logo.svg
  prometheus/prometheus-volume/data/chunks_head/000001
  prometheus/prometheus-volume/data/queries.active
  prometheus/prometheus-volume/data/wal/00000000
  prometheus/prometheus-volume/data/wal/00000001
Labels: enhancement

#125 fix : 폰트 오류 수정완료
  frontend/src/components/AuthModalStyle.jsx
  frontend/src/font.css
  frontend/src/styles/GlobalStyle.js
  grafana/grafana-volume/grafana.db
Labels: enhancement

#131 Front/feat/#107
  backend/image/views.py
  frontend/src/components/Carousel2.jsx
  frontend/src/components/Carousel3.jsx
  frontend/src/components/Carousel4.jsx
  frontend/src/components/Custom/CustomCarousel.jsx
  frontend/src/pages/AlbumPage.jsx
  frontend/src/pages/ChooseFramePage.jsx
  frontend/src/pages/ConvertAIPage.jsx
  frontend/src/pages/FramePage.jsx
  frontend/src/pages/UploadImagePage.jsx
Labels: enhancement, style

#140 [front/feat/#134]html2canvas 상에서 외부 이미지 캡쳐 불가능 -> 해결 작업 진행
  backend/backend_project/settings.py
  frontend/Dockerfile
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Custom/CustomCarousel.jsx
  frontend/src/pages/TestPage.jsx
Labels: enhancement

#141 [front/feat] 페이지 넘어갈 때 로딩 구현
  frontend/src/pages/AlbumPage.jsx
  frontend/src/pages/ConvertAIPage.jsx
  frontend/src/pages/UploadImagePage.jsx
Labels: enhancement

#149 Front/feat/#143
  frontend/src/assets/images/emoji.png
  frontend/src/assets/images/save.png
  frontend/src/components/Custom/CustomCarousel.jsx
  frontend/src/components/Custom/CustomEmoji.jsx
  frontend/src/components/Custom/CustomPhoto.jsx
  frontend/src/components/Custom/CustomTextBox.jsx
  frontend/src/pages/CustomizingPage.jsx
Labels: bug, enhancement, style

#153 [Front/feat] 추가 기능 구현
  frontend/src/assets/images/albumIcon.png
  frontend/src/components/Custom/CustomCarousel.jsx
  frontend/src/components/FloatingImage.jsx
  frontend/src/components/LoginModal.jsx
  frontend/src/components/SignUpModal.jsx
  frontend/src/pages/AlbumPage.jsx
  frontend/src/pages/CustomizingPage.jsx
  frontend/src/pages/FramePage.jsx
Labels: enhancement

#155 [front/design/#151] 전체 디자인 수정 초안
  frontend/package-lock.json
  frontend/src/assets/images/upload.png
  frontend/src/components/Carousel1.jsx
  frontend/src/components/Carousel2.jsx
  frontend/src/components/Carousel3.jsx
  frontend/src/components/Carousel4.jsx
  frontend/src/components/LeftAIShift.jsx
  frontend/src/components/LoadingAnimation.jsx
  frontend/src/components/PageShiftBtn.jsx
  frontend/src/components/RightAIShift.jsx
  frontend/src/components/UploadImage.jsx
  frontend/src/font.css
  frontend/src/pages/AlbumPage.jsx
  frontend/src/pages/ChooseFramePage.jsx
  frontend/src/pages/ConvertAIPage.jsx
  frontend/src/pages/CustomizingPage.jsx
  frontend/src/pages/FramePage.jsx
  frontend/src/pages/UploadImagePage.jsx
Labels: invalid

#160 [front/error/#156] 앨범 이미지 fade-up 간헐적으로 안되는 오류 수정
  frontend/src/pages/AlbumPage.jsx
Labels: enhancement

#166 [Front/feat] 프레임 비율 맞추기
  frontend/src/components/Custom/CustomCarousel.jsx
  frontend/src/pages/CustomizingPage.jsx
Labels: enhancement
