Repository 2023SB-TeamJ/2023SB-Team-J, pull requests merged in 2023-08, with the labels that each got.

#169 feat : 프로그레스 바 구현
  frontend/src/components/ProgressBar.jsx
  frontend/src/components/UploadImage.jsx
  frontend/src/pages/ChooseFramePage.jsx
  frontend/src/pages/ConvertAIPage.jsx
  frontend/src/pages/CustomizingPage.jsx
  frontend/src/pages/FramePage.jsx
  frontend/src/pages/UploadImagePage.jsx
Labels: enhancement

#179 [Front/design] 페이지 반응형 1차 구현
  frontend/src/components/Carousel1.jsx
  frontend/src/components/Carousel2.jsx
  frontend/src/components/Carousel3.jsx
  frontend/src/components/Carousel4.jsx
  frontend/src/components/Loading.jsx
  frontend/src/components/Logo.jsx
  frontend/src/components/Name.jsx
  frontend/src/components/SignBtn.jsx
  frontend/src/pages/AlbumPage.jsx
  frontend/src/pages/ChooseFramePage.jsx
  frontend/src/pages/ConvertAIPage.jsx
  frontend/src/pages/UploadImagePage.jsx
  frontend/src/styles/GlobalStyle.js
Labels: style

#182 [front/design]
  frontend/src/Router.jsx
  frontend/src/assets/images/aframe_1.png
  frontend/src/assets/images/aframe_2.png
  frontend/src/assets/images/aframe_3.png
  frontend/src/assets/images/bframe_1.png
  frontend/src/assets/images/bframe_2.png
  frontend/src/assets/images/frame1.PNG
  frontend/src/assets/images/frame2.PNG
  frontend/src/assets/images/frame3.PNG
  frontend/src/components/AlbumDetailModal.jsx
  frontend/src/components/Custom/CustomCarousel.jsx
  frontend/src/components/Header.jsx
  frontend/src/components/HeaderMain.jsx
  frontend/src/components/PageShiftBtn.jsx
  frontend/src/components/ProgressBar.jsx
  frontend/src/contexts/AuthContext.jsx
  frontend/src/index.jsx
  frontend/src/pages/ConvertAIPage.jsx
  frontend/src/pages/CustomizingPage.jsx
  frontend/src/pages/FramePage.jsx
Labels: bug, enhancement, style

#185 Front/design/#180
  frontend/src/components/Carousel1.jsx
  frontend/src/components/Carousel2.jsx
  frontend/src/components/Carousel3.jsx
  frontend/src/components/Carousel4.jsx
  frontend/src/components/PageShiftBtn.jsx
  frontend/src/pages/ChooseFramePage.jsx
  frontend/src/pages/ConvertAIPage.jsx
  frontend/src/pages/MainPage.jsx
  frontend/src/pages/UploadImagePage.jsx
Labels: style

#192 Front/error/#187 캐러셀 기능 동적으로 변경
  frontend/src/components/Carousel1.jsx
  frontend/src/components/Carousel2.jsx
  frontend/src/components/Carousel3.jsx
  frontend/src/components/Carousel4.jsx
  frontend/src/components/Custom/CustomCarousel.jsx
Labels: style

#193 fix : 커스터마이징 페이지 -> 리사이즈 버튼을 마우스 hover 될때만 보이게 수정, fix : 500 에러 해결
  backend/backend_project/settings.py
  frontend/src/components/Custom/CustomEmoji.jsx
  frontend/src/components/Custom/CustomPhoto.jsx
Labels: bug

#194 [front/design/#190] 디자인 수정
  frontend/src/components/AlbumDetailModal.jsx
  frontend/src/components/FloatingImage.jsx
  frontend/src/components/HeaderAlbum.jsx
  frontend/src/components/HeaderCustom.jsx
  frontend/src/components/Logo.jsx
  frontend/src/components/Name.jsx
  frontend/src/font.css
  frontend/src/pages/AlbumPage.jsx
  frontend/src/pages/ChooseFramePage.jsx
  frontend/src/pages/CustomizingPage.jsx
  frontend/src/pages/MainPage.jsx
Labels: enhancement
